export const AppErrorCode = {
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
};
